### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by LisandraBrave** [qwerty0s/opengl-testing#2]
How the fuck am I supposed to
```
git clone
make
```
if you don't tell me how to?

**Comment by LisandraBrave** [comment]
![image](https://user-images.githubusercontent.com/8226662/72757669-321b3b00-3b96-11ea-85c8-1a1f6850648d.png)

**Comment by megidont** [comment]
For setting up your build environment, we recommend OpenJDK and to follow the instructions on this website if you are using an IDE: [https://www.lwjgl.org/download](url)

If you are not using an IDE, we recommend you research how to set up your CLASSPATH environment variable to include the packages within. After that, you can simply build using "javac [filename].java" and it will build.
